name: GitHub Actions UAT

on: push
jobs:
  builds:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - name: GitHub Actions UAT
          run: echo "This build successfully executed"
